### ISSUE TITLE
Last message never sent

### ISSUE THREAD

**Issue by dohnto** [uken/fluent-plugin-elasticsearch#155]
Hi, I am beginning with fluentd and elastic search. I use this configuration 

```
<source>
    @type tail
     path /fluentd/log/log
     pos_file /fluentd/log/log.pos
     tag test
     format multiline
     format_firstline /\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}/
     format1 /^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}).(?<ms>\d{3})(?<us>\d{3}) (?<log_level>[^:]*): \[(?<pid>[^:]*)\]: (?<message>.*)/
     time_format %Y/%m/%d %H:%M:%S
</source>
<match test>
   @type elasticsearch
    host elastic.dev
    port 9200
    flush_interval 10s
    type_name my_type
    utc_index false
    logstash_format true
    logstash_prefix my_prefix
</match>
```

And I append single line to my file, but until I append a next line, the previous is never send. Eventhough I stop the fluend gracefully, the last message is never send to elastic search and I always miss last logging message.

 Is this behaviour normal? How to avoid this? Thanks

**Comment by pitr** [comment]
I tried this config:

```
<match to.es>
  @type elasticsearch
  logstash_format true
  flush_interval 2s
</match>

<source>
  @type tail
  path log
  tag to.es
  format none
</source>
```

And running `echo testing >> log`, worked every time. Perhaps the issue is with using multiline format and custom regex in tail plugin, maybe it's too greedy (I've never used multiline in_tail). Try replacing `@type elasticsearch` with [@type stdout](http://docs.fluentd.org/articles/out_stdout) to confirm this.

Feel free to reopen if the problem is with this plugin.

**Comment by dohnto** [comment]
I missed `multiline_flush_interval` option. Thanks.

**Comment by pitr** [comment]
no problem, glad I could help
