### ISSUE TITLE
Trying to use fluent-plugin-elasticsearch on CentOS 7

### ISSUE THREAD

**Issue by ChrisCGH** [uken/fluent-plugin-elasticsearch#254]
#### Problem

I'm trying to use the fluent-plugin-elasticsearch on CentOS 7, but when I try to install with "gem install fluent-plugin-elasticsearch" the installer tries to install all the dependencies and in particular serverengine 2.0.5 which depends on ruby >= 2.1.0. However, CentOS 7 only has ruby 2.0.0.
I can force the plugin to install by running "gem install fluent-plugin-elasticsearch -f", and everything appears to work (I am seeing logs generated by td-agent appear in kibana), but is the serverengine dependency on ruby 2.1.0 going to cause issues?

**Comment by cosmo0920** [comment]
td-agent2 bundled Ruby 2.1:
https://github.com/treasure-data/omnibus-td-agent/blob/master/config/projects/td-agent2.rb#L19

And we don't recommend to use Ruby 2.0 because this version of Ruby had been reached EOL.
https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/
If you strongly want to use Ruby 2.0, please use it at your own risk.

**Comment by cosmo0920** [comment]
Any response?

**Comment by cosmo0920** [comment]
No response. Closing.
