### ISSUE TITLE
"flush_mode immediate" is not work

### ISSUE THREAD

**Issue by jushiyuan** [uken/fluent-plugin-elasticsearch#348]
#### Problem

...

#### Expected Behavior or What you need to ask
Does this plugin support `flush_mode immediate`?If I set this, it doesn't work. I know i can set `flush_interval 1s` to speed up the flush,but it's still not immediate.
...

#### Using Fluentd and ES plugin versions

* OS version
* Fluentd v1.1
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES plugin 2.4.1
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock

**Comment by cosmo0920** [comment]
Fill issue template, please.

**Comment by cosmo0920** [comment]
> Does this plugin support flush_mode immediate?If I set this, it doesn't work. I know i can set flush_interval 1s to speed up the flush,but it's still not immediate.

This configuration parameter does not come from fluent-plugin-elasticsearch.
It comes from [Fluentd's buffer mechanism](https://docs.fluentd.org/v1.0/articles/buffer-section#flushing-parameters).

How about use new structured style configuration for buffer like as the below?

```aconf
<buffer>
  flush_mode immediate
</buffer>
```

Otherwise, Fluentd will complain like as:

```log
2018-01-23 18:06:46 +0900 [warn]: parameter 'flush_mode' in <match my.logs>
  @type elasticsearch
  host "localhost"
  flush_mode immediate
</match> is not used.
```

Because Fluentd's `compat_parameters` plugin helper does not handle `flush_mode` parameter in [`#compat_parameters_convert`](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/compat_parameters.rb#L28-L42).

If you feel this behavior is a pitfall, could you report this behavior in [Fluentd](https://github.com/fluent/fluentd)?

**Comment by jushiyuan** [comment]
@cosmo0920 Well, I know. Thank you very much.
