### ISSUE TITLE
add parameter for enable checking bulk request response time

### ISSUE THREAD

**Issue by chikinchoi** [uken/fluent-plugin-elasticsearch#833]
#### Problem

Hi,

We are using the fluentd to send logs to elasticsearch now and we found that there are a lot of "slow_flush" warning in the fluentd log. I understand that the fluentd send logs to elasticsearch by using the bulk api request. Therefore, we checked if there is any slow_index in elasticsearch performance but it seems the elasticsearch performance is good. 
Therefore, I would like to know is there any parameter that I can add to fluentd config to enable checking the response time of the bulk request? 

Thank you!!

**Comment by cosmo0920** [comment]
> Therefore, I would like to know is there any parameter that I can add to fluentd config to enable checking the response time of the bulk request?

This response time only dumped with `with_transport_log true`.
Otherwise, no option to retrieve response time from elasticsearch-ruby client.
Could you send your request to make retrievable response time feature in [elasticsearch-ruby client repository](https://github.com/elastic/elasticsearch-ruby)?
Thanks in advance.

**Comment by cosmo0920** [comment]
I decided this issue should be closed.
Because this feature request is impossible to implement on ES plugin side only.
